steps:
  - name: 'bash'
    args: ["-c", "chmod 777 ./Gemfile.lock"]
  - name: 'bash'
    args: ["-c", "chmod 777 ./_site"]    
  - name: jekyll/builder:latest
    entrypoint: jekyll
    args: ["build"]  
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-d", "./_site", "gs://jorg.eikens.com"]