steps:
  - name: 'bash'
    args: ["-c", "chmod 777 ./Gemfile.lock"]
  - name: 'bash'
    args: ["-c", "chmod 777 -R ."]
  - name: 'bash'
    args: ["-c", "cat ./_config.yml"]
  - name: 'bash'
    args: ["-c", "rm -r ./_site"]    
  - name: jekyll/builder:latest
    entrypoint: jekyll
    args: ["build", "--verbose"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-d", "./_site", "gs://jorg.eikens.com"]
    