# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chown jekyll:jekyll -R /srv/jekyll && gem install bundler && jekyll build && ls -al /src/jekyll/_site"
          ls -al ${{ github.workspace }}/_site

      - name: Upload the site to Google Cloud Storage
        env:
          GCS-SECRET: ${{ secrets.JORG_EIKENS_COM_D211EE91E559 }}
        run: |
          echo $GCS-SECRET > ${{ github.workspace }}/secret.json
          docker run \
          -v ${{ github.workspace }}:/home \
          gcr.io/google.com/cloudsdktool/cloud-sdk:latest gcloud auth activate-service-account --key-file=/home/secret.json && gsutil rsync -R /home/_site gs://jorg.eikens.com"

